package com.dsproj.filmmanagmentdsproject;
// Jalil Guliyev 220315102
public class FilmJ implements Comparable<FilmJ> {
    private String name; // Film name
    private int filmId; // Unique identifier for the film
    private String genre; // Film genre
    private int releaseYear; // Year the film was released
    private double totalRevenue; // Total revenue generated by the film
    private LinkedListJ<ActorJ> actorList; // Custom linked list of actors in the film
    private double popularity; // Popularity of the film based on ratings

    // Constructor to initialize the film details
    public FilmJ(String name, int filmId, String genre, int releaseYear) {
        this.name = name;
        this.filmId = filmId;
        this.genre = genre;
        this.releaseYear = releaseYear;
        this.totalRevenue = 0.0; // Initialize revenue to zero
        this.actorList = new LinkedListJ<>(); // Initialize the actor list
        this.popularity = 0.0; // Initialize popularity to zero
    }

    // Adds an actor to the film's actor list
    public void addActor(ActorJ actor) {
        if (!actorList.contains(actor)) {
            actorList.add(actor);
            actor.addFilm(this); // Ensure the actor knows about this film
        }
    }

    // Removes an actor from the film's actor list
    public void removeActor(ActorJ actor) {
        if (actorList.contains(actor)) {
            actorList.remove(actor);
            actor.removeFilm(this); // Ensure the actor's list is updated
        }
    }

    // Checks if an actor is part of the film
    public boolean hasActor(ActorJ actor) {
        return actorList.contains(actor);
    }

    // Getter and setter methods for the film's attributes
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getFilmId() {
        return filmId;
    }

    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public int getReleaseYear() {
        return releaseYear;
    }

    public void setReleaseYear(int releaseYear) {
        this.releaseYear = releaseYear;
    }

    public double getTotalRevenue() {
        return totalRevenue;
    }

    public void setTotalRevenue(double totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    // New method to update popularity based on average rating
    public void updatePopularity(double averageRating) {
        this.popularity = averageRating;
    }

    // Override compareTo to allow sorting by film name
    @Override
    public int compareTo(FilmJ otherFilm) {
        return this.name.compareTo(otherFilm.name); // Compare by name for sorting
    }

    @Override
    public String toString() {
        return "Film Name: " + name + ", ID: " + filmId + ", Genre: " + genre + 
               ", Release Year: " + releaseYear + ", Revenue: " + totalRevenue + ", Popularity: " + popularity;
    }
}